# Config file for automatic testing at travis-ci.org
language: python
sudo: false

python:
  - "3.7"
  - "3.6"
  - "pypy"

# command to install dependencies
install: pip install -r requirements.txt

# lint before running tests
before_script:
  - 'if [ "$TRAVIS_PYTHON_VERSION" != "2.6" ]; then flake8 pvl tests; fi'

# command to run tests
script: py.test tests
