# Config file for automatic testing at travis-ci.org
language: python
sudo: false

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies
install: pip install -r requirements.txt

# lint before running tests
before_script: flake8 pvl tests

# command to run tests
script: py.test tests
